### ISSUE TITLE
Bug in check for conversion success

### ISSUE THREAD

**Issue by musteresel** [Tosberino/prime#1]
https://github.com/Tosberino/prime/blob/4794cea6d63de21e78303e63cec06b3a79188eca/main.cpp#L14-L17

[`atoi`](https://en.cppreference.com/w/c/string/byte/atoi) doesn't throw an exception.  Consider using [`stoi`](https://en.cppreference.com/w/cpp/string/basic_string/stol).

**Comment by Tosberino** [comment]
Thanks. I changed it.
